[package]
name = "knn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[snake]
name = "knn"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.6"
pyo3 = { version = "0.20.1", features = ["extension-module"] }
