[project]
name = "knn"
version = "0.1.0"
description = "kNN in Rust for Python"
authors = ["Prayson W. Daniel <praysonpi@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
scikit-learn = "1.3.2.*"
maturin = "1.4.0.*"
pytest = "7.4.4.*"
ruff = "0.1.9.*"
pip = "23.3.2.*"
black = "23.12.1.*"
