[project]
name = "dev.io"
version = "0.1.0"
description = "Add a short description here"
authors = ["Prayson W. Daniel <praysonpi@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
scikit-learn = "1.3.0.*"
pandas = "2.1.0.*"
pymc = "5.7.2.*"
ipykernel = "6.25.1.*"
nbformat = "5.9.2.*"
plotly = "5.16.1.*"
black = "23.7.0.*"
pytest = "7.4.1.*"
statsmodels = "0.14.0.*"
ruff = "0.0.287.*"
python-graphviz = "0.20.1.*"
jinja2 = "3.1.2.*"
patsy = "0.5.3.*"
flaml = "2.1.1.*"
hiplot = "0.1.33.*"
bambi = "0.13.0.*"
mljar-supervised = "1.1.1.*"
deepchecks = "0.3.2.*"
patchworklib = "0.6.3.*"
seaborn = "0.12.2.*"
openpyxl = "3.1.2.*"
pyarrow = "13.0.0.*"
autogluon = "0.8.2.*"
bokeh = "3.2.2.*"
