[project]
name = "emotions"
version = "0.1.0"
description = "LLM emoitons"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "instructor>=1.4.3",
    "phidata>=2.4.34",
    "polars>=1.7.1",
]

[tool.uv]
dev-dependencies = ["pytest>=8.3.3"]
