[project]
name = "simplicity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = ["pytest>=8.3.4", "ruff>=0.8.1"]

[tool.pytest.ini_options]
pythonpath = ["bank"]
